

name: CS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install csunit
      run: sudo apt install -y libcsunit-dev
    - name: make
      run: make
    - name: make test
      run: make test
